const GET_COSMETICS_LIST_REQUEST = 'GET_COSMETICS_LIST_REQUEST';
const GET_COSMETICS_LIST_SUCCESS = 'GET_COSMETICS_LIST_SUCCESS';
const GET_COSMETICS_LIST_FAILURE = 'GET_COSMETICS_LIST_FAILURE';

const types = {
    GET_COSMETICS_LIST_REQUEST,
    GET_COSMETICS_LIST_SUCCESS,
    GET_COSMETICS_LIST_FAILURE,
}

export default types;
