const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FAILURE = 'GET_USER_FAILURE';

const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

const DELETE_PROFILE_PICTURE_SUCCESS = 'DELETE_PROFILE_PICTURE_SUCCESS';
const DELETE_PROFILE_PICTURE_FAILURE = 'DELETE_PROFILE_PICTURE_SUCCESS';

const ADD_COSMETIC_SUCCESS = 'ADD_COSMETIC_SUCCESS';
const ADD_COSMETIC_FAILURE = 'ADD_COSMETIC_SUCCESS';

const DELETE_COSMETIC_SUCCESS = 'DELETE_COSMETIC_SUCCESS';
const DELETE_COSMETIC_FAILURE = 'DELETE_COSMETIC_FAILURE';

const ADD_PALETTE_SUCCESS = 'ADD_PALETTE_SUCCESS';
const ADD_PALETTE_FAILURE = 'ADD_PALETTE_FAILURE';

const DELETE_PALETTE_SUCCESS = 'DELETE_PALETTE_SUCCESS';
const DELETE_PALETTE_FAILURE = 'DELETE_PALETTE_FAILURE';

const types = {
    CREATE_USER_SUCCESS,
    CREATE_USER_FAILURE,
	GET_USER_SUCCESS,
	GET_USER_FAILURE,
	UPDATE_USER_SUCCESS,
	UPDATE_USER_FAILURE,
	DELETE_USER_SUCCESS,
	DELETE_USER_FAILURE,
	DELETE_PROFILE_PICTURE_SUCCESS,
	DELETE_PROFILE_PICTURE_FAILURE,
	ADD_COSMETIC_SUCCESS,
	ADD_COSMETIC_FAILURE,
	DELETE_COSMETIC_SUCCESS,
	DELETE_COSMETIC_FAILURE,
	ADD_PALETTE_SUCCESS,
	ADD_PALETTE_FAILURE,
	DELETE_PALETTE_SUCCESS,
	DELETE_PALETTE_FAILURE
}

export default types;
