const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

const DELETE_PROFILE_PICTURE_SUCCESS = 'DELETE_PROFILE_PICTURE_SUCCESS';
const DELETE_PROFILE_PICTURE_FAILURE = 'DELETE_PROFILE_PICTURE_SUCCESS';

const types = {
    CREATE_USER_SUCCESS,
    CREATE_USER_FAILURE,
	DELETE_PROFILE_PICTURE_SUCCESS,
	DELETE_PROFILE_PICTURE_FAILURE
}

export default types;
